services:
  rust-query-example-db:
    image: postgres:14.15-alpine3.21
    ports: 
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER : user
      POSTGRES_PASSWORD : admin
      POSTGRES_DB : users
  
