services:
  rust-query-example-db:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER : user
      POSTGRES_PASSWORD : admin
      POSTGRES_DB : users
  
